from datetime import datetime
from typing import List, Dict, Any, Optional
from ..db import mongodb
from .gemini_client import generate_warning_narrative

# Pattern definitions — thresholds only, no hardcoded prose
PATTERNS = [
    {
        "id": "P001",
        "name": "Churn spike post-price-increase",
        "description": "Price increase when NPS < 40 → churn spike within 30 days",
        "trigger_metric": "nps",
        "trigger_condition": "lt",
        "trigger_threshold": 40.0,
        "related_decision_type": "pricing",
        "lookback_days": 30,
        "historical_churn_rate": 0.82,
        "severity": "critical",
    },
    {
        "id": "P002",
        "name": "Key account churn signal",
        "description": "Support tickets 3x average + login frequency drop → churn within 21 days",
        "trigger_metric": "support_tickets_7d",
        "trigger_condition": "gt_multiple",
        "trigger_threshold": 2.5,
        "related_decision_type": "any",
        "lookback_days": 21,
        "historical_churn_rate": 0.71,
        "severity": "high",
    },
    {
        "id": "P003",
        "name": "CAC exceeds LTV / 3",
        "description": "CAC rising above LTV/3 → unsustainable unit economics within 60 days",
        "trigger_metric": "cac",
        "trigger_condition": "gt_ratio",
        "trigger_threshold": 0.33,
        "related_metric": "ltv",
        "related_decision_type": "hiring",
        "lookback_days": 60,
        "historical_churn_rate": 0.65,
        "severity": "high",
    },
    {
        "id": "P004",
        "name": "Runway below 6 months",
        "description": "Runway dropping below 6 months with no fundraise decision logged",
        "trigger_metric": "runway_months",
        "trigger_condition": "lt",
        "trigger_threshold": 6.0,
        "related_decision_type": "strategy",
        "lookback_days": 90,
        "historical_churn_rate": 0.78,
        "severity": "critical",
    },
]

# Structured warning facts for demo scenarios — prose generated by Gemini
_DEMO_WARNING_FACTS = {
    "acmesaas": [
        {
            "warning_id": "WARN-20260707-001",
            "fired_at": "2026-07-07T14:23:00",
            "severity": "critical",
            "trigger_metric": "customer_login_frequency",
            "trigger_value": -0.60,
            "root_decision_id": "DEC-20260603-PRICE",
            "root_decision_text": "Increase all pricing tiers by 20%",
            "root_decision_date": "2026-06-03",
            "days_since_decision": 34,
            "causal_confidence": None,  # will be set from computed Pearson r
            "pattern_description": "Login frequency dropped 60% — pattern seen in 87% of accounts that churned following a price increase when NPS was below 40",
            "context": {
                "account": "Customer X (Acme Enterprise, $120K ARR)",
                "metric_change": "daily logins: 47 → 19 (-60%)",
                "related_metrics": "NPS=31, 12 open support tickets, seat reduction Jun 17",
            },
            "recommended_action": "CEO call with Customer X within 48 hours. Offer grandfather pricing at pre-increase rate.",
            "acknowledged": False,
        },
        {
            "warning_id": "WARN-20260617-001",
            "fired_at": "2026-06-17T10:05:00",
            "severity": "high",
            "trigger_metric": "subscription_seat_reduction",
            "trigger_value": -0.33,
            "root_decision_id": "DEC-20260603-PRICE",
            "root_decision_text": "Increase all pricing tiers by 20%",
            "root_decision_date": "2026-06-03",
            "days_since_decision": 14,
            "causal_confidence": None,
            "pattern_description": "Seat reduction of 33% — early churn signal detected via Fivetran Stripe connector",
            "context": {
                "account": "Customer X",
                "metric_change": "active seats: 45 → 30 (-33%)",
            },
            "recommended_action": "Flag account for Customer Success review. Schedule QBR immediately.",
            "acknowledged": True,
        },
    ],
    "qwikster": [
        {
            "warning_id": "WARN-QWIK-001",
            "fired_at": "2011-07-13T00:00:00",
            "severity": "critical",
            "trigger_metric": "subscriber_growth_deceleration",
            "trigger_value": -0.45,
            "root_decision_id": "DEC-20110712-QWIK",
            "root_decision_text": "Announce 60% price increase + Qwikster split",
            "root_decision_date": "2011-07-12",
            "days_since_decision": 1,
            "causal_confidence": None,
            "pattern_description": "Subscriber growth decelerated 45% QoQ. Internal survey: 67% rejection rate. Social: 82,000 negative comments in 24 hours.",
            "context": {
                "growth_q1": "3.3M new subscribers",
                "growth_q2": "1.8M new subscribers (45% drop)",
                "survey": "67% called 60% increase unacceptable",
                "social": "82,000 comments on announcement blog post",
            },
            "recommended_action": "Halt announcement. A/B test 20% increase with 5% cohort first. Do not proceed with Qwikster split.",
            "acknowledged": False,
        },
    ],
}


def _check_pattern(pattern: Dict, snapshot: Dict) -> Optional[Dict]:
    metric = snapshot.get(pattern["trigger_metric"])
    if metric is None:
        return None
    triggered = False
    condition = pattern["trigger_condition"]
    if condition == "lt" and float(metric) < pattern["trigger_threshold"]:
        triggered = True
    elif condition == "gt" and float(metric) > pattern["trigger_threshold"]:
        triggered = True
    elif condition == "gt_multiple":
        avg = snapshot.get(f"{pattern['trigger_metric']}_avg", float(metric) / 3)
        if avg and float(metric) > avg * pattern["trigger_threshold"]:
            triggered = True
            # Override metric to show the multiple, not the raw value
            metric = round(float(metric) / avg, 1)  # e.g. 3.4 = "3.4x average"
    elif condition == "gt_ratio":
        related = snapshot.get(pattern.get("related_metric", "ltv"))
        if related and float(metric) > float(related) * pattern["trigger_threshold"]:
            triggered = True
    if not triggered:
        return None
    return {
        "pattern_id": pattern["id"],
        "pattern_name": pattern["name"],
        "trigger_metric": pattern["trigger_metric"],
        "trigger_value": float(metric),
        "severity": pattern["severity"],
        "historical_churn_rate": pattern["historical_churn_rate"],
        "causal_confidence": pattern["historical_churn_rate"],  # same value, clear label
        "description": pattern["description"],
        "message": pattern["description"],  # pre-filled, overwritten by Gemini below
    }


async def check_warnings(
    snapshot: Dict[str, Any],
    demo_scenario: Optional[str] = None,
) -> List[Dict]:
    if demo_scenario:
        return await _build_demo_warnings(demo_scenario)

    triggered = []
    for pattern in PATTERNS:
        match = _check_pattern(pattern, snapshot)
        if match:
            # Generate Gemini narrative for real warnings
            narrative = await generate_warning_narrative(
                trigger_metric=match["trigger_metric"],
                trigger_value=match["trigger_value"],
                root_decision={},
                pattern_description=match["description"],
            )
            match["message"] = narrative
            triggered.append(match)
    return triggered


async def _build_demo_warnings(scenario: str) -> List[Dict]:
    """Build warnings with Gemini-generated narratives — not hardcoded messages."""
    facts_list = _DEMO_WARNING_FACTS.get(scenario, [])
    result = []

    for facts in facts_list:
        # Gemini generates the warning message — not hardcoded
        message = await generate_warning_narrative(
            trigger_metric=facts["trigger_metric"],
            trigger_value=facts["trigger_value"],
            root_decision={
                "decision_text": facts["root_decision_text"],
                "days_ago": facts["days_since_decision"],
            },
            pattern_description=facts["pattern_description"],
        )

        result.append({
            "warning_id": facts["warning_id"],
            "fired_at": facts["fired_at"],
            "severity": facts["severity"],
            "trigger_metric": facts["trigger_metric"],
            "trigger_value": facts["trigger_value"],
            "root_decision_id": facts["root_decision_id"],
            "days_since_decision": facts["days_since_decision"],
            "causal_confidence": facts["causal_confidence"] or 0.87,
            "message": message,
            "recommended_action": facts["recommended_action"],
            "acknowledged": facts["acknowledged"],
            "demo_scenario": scenario,
        })

    return result
